# Generated by Django 4.0.5 on 2022-07-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RetailStore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('store_id', models.IntegerField()),
                ('sku', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
